### ISSUE TITLE
Major update needed, breaking changes, the future of the project!

### ISSUE THREAD

**Issue by antoniojps** [HenriqueSilva2/ArticlesApp-fe#2]
Hey dear Henrique Silva,
First of all I'd like to let you know that I really like your website, I write articles everyday in it, the feature where you can edit the code style with the shortcuts is really good!

However, there's one thing that bothers me and that you could definitely do better, please remove all the unnecessary React code, it's really clunky.

Please can you provide a Vue JS version of this project! It's the future :green_heart: :rocket:

**Comment by HenriqueSilva2** [comment]
Hey PhD António Santos,

Hope you are having an incredible user experience using this resource. 

I saw your new rep and i see that you started to use React. 
You're a man now, congrats! 

Best regards 💯 🥇

**Comment by antoniojps** [comment]
Thanks!
